// Generated by gencpp from file robot_planning/CartesianInterpolationResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_PLANNING_MESSAGE_CARTESIANINTERPOLATIONRESPONSE_H
#define ROBOT_PLANNING_MESSAGE_CARTESIANINTERPOLATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_planning
{
template <class ContainerAllocator>
struct CartesianInterpolationResponse_
{
  typedef CartesianInterpolationResponse_<ContainerAllocator> Type;

  CartesianInterpolationResponse_()
    : joint_trajectory()
    , success(false)
    , message()  {
    }
  CartesianInterpolationResponse_(const ContainerAllocator& _alloc)
    : joint_trajectory(_alloc)
    , success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_trajectory_type;
  _joint_trajectory_type joint_trajectory;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CartesianInterpolationResponse_

typedef ::robot_planning::CartesianInterpolationResponse_<std::allocator<void> > CartesianInterpolationResponse;

typedef boost::shared_ptr< ::robot_planning::CartesianInterpolationResponse > CartesianInterpolationResponsePtr;
typedef boost::shared_ptr< ::robot_planning::CartesianInterpolationResponse const> CartesianInterpolationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator1> & lhs, const ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.joint_trajectory == rhs.joint_trajectory &&
    lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator1> & lhs, const ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ba03139604ba18f20c411a4ea79d0af";
  }

  static const char* value(const ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ba03139604ba18fULL;
  static const uint64_t static_value2 = 0x20c411a4ea79d0afULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_planning/CartesianInterpolationResponse";
  }

  static const char* value(const ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] joint_trajectory  # Flattened array of joint configurations\n"
"bool success\n"
"string message \n"
;
  }

  static const char* value(const ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_trajectory);
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CartesianInterpolationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_planning::CartesianInterpolationResponse_<ContainerAllocator>& v)
  {
    s << indent << "joint_trajectory[]" << std::endl;
    for (size_t i = 0; i < v.joint_trajectory.size(); ++i)
    {
      s << indent << "  joint_trajectory[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_trajectory[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_PLANNING_MESSAGE_CARTESIANINTERPOLATIONRESPONSE_H
