// Generated by gencpp from file robot_planning/PlanPath.msg
// DO NOT EDIT!


#ifndef ROBOT_PLANNING_MESSAGE_PLANPATH_H
#define ROBOT_PLANNING_MESSAGE_PLANPATH_H

#include <ros/service_traits.h>


#include <robot_planning/PlanPathRequest.h>
#include <robot_planning/PlanPathResponse.h>


namespace robot_planning
{

struct PlanPath
{

typedef PlanPathRequest Request;
typedef PlanPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanPath
} // namespace robot_planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_planning::PlanPath > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::robot_planning::PlanPath&) { return value(); }
};

template<>
struct DataType< ::robot_planning::PlanPath > {
  static const char* value()
  {
    return "robot_planning/PlanPath";
  }

  static const char* value(const ::robot_planning::PlanPath&) { return value(); }
};


// service_traits::MD5Sum< ::robot_planning::PlanPathRequest> should match
// service_traits::MD5Sum< ::robot_planning::PlanPath >
template<>
struct MD5Sum< ::robot_planning::PlanPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_planning::PlanPath >::value();
  }
  static const char* value(const ::robot_planning::PlanPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_planning::PlanPathRequest> should match
// service_traits::DataType< ::robot_planning::PlanPath >
template<>
struct DataType< ::robot_planning::PlanPathRequest>
{
  static const char* value()
  {
    return DataType< ::robot_planning::PlanPath >::value();
  }
  static const char* value(const ::robot_planning::PlanPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_planning::PlanPathResponse> should match
// service_traits::MD5Sum< ::robot_planning::PlanPath >
template<>
struct MD5Sum< ::robot_planning::PlanPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_planning::PlanPath >::value();
  }
  static const char* value(const ::robot_planning::PlanPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_planning::PlanPathResponse> should match
// service_traits::DataType< ::robot_planning::PlanPath >
template<>
struct DataType< ::robot_planning::PlanPathResponse>
{
  static const char* value()
  {
    return DataType< ::robot_planning::PlanPath >::value();
  }
  static const char* value(const ::robot_planning::PlanPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_PLANNING_MESSAGE_PLANPATH_H
