// Generated by gencpp from file robot_planning/RobotPose.msg
// DO NOT EDIT!


#ifndef ROBOT_PLANNING_MESSAGE_ROBOTPOSE_H
#define ROBOT_PLANNING_MESSAGE_ROBOTPOSE_H

#include <ros/service_traits.h>


#include <robot_planning/RobotPoseRequest.h>
#include <robot_planning/RobotPoseResponse.h>


namespace robot_planning
{

struct RobotPose
{

typedef RobotPoseRequest Request;
typedef RobotPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotPose
} // namespace robot_planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_planning::RobotPose > {
  static const char* value()
  {
    return "88bd561bfe99b318bb370cf7b0dd2f58";
  }

  static const char* value(const ::robot_planning::RobotPose&) { return value(); }
};

template<>
struct DataType< ::robot_planning::RobotPose > {
  static const char* value()
  {
    return "robot_planning/RobotPose";
  }

  static const char* value(const ::robot_planning::RobotPose&) { return value(); }
};


// service_traits::MD5Sum< ::robot_planning::RobotPoseRequest> should match
// service_traits::MD5Sum< ::robot_planning::RobotPose >
template<>
struct MD5Sum< ::robot_planning::RobotPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_planning::RobotPose >::value();
  }
  static const char* value(const ::robot_planning::RobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_planning::RobotPoseRequest> should match
// service_traits::DataType< ::robot_planning::RobotPose >
template<>
struct DataType< ::robot_planning::RobotPoseRequest>
{
  static const char* value()
  {
    return DataType< ::robot_planning::RobotPose >::value();
  }
  static const char* value(const ::robot_planning::RobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_planning::RobotPoseResponse> should match
// service_traits::MD5Sum< ::robot_planning::RobotPose >
template<>
struct MD5Sum< ::robot_planning::RobotPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_planning::RobotPose >::value();
  }
  static const char* value(const ::robot_planning::RobotPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_planning::RobotPoseResponse> should match
// service_traits::DataType< ::robot_planning::RobotPose >
template<>
struct DataType< ::robot_planning::RobotPoseResponse>
{
  static const char* value()
  {
    return DataType< ::robot_planning::RobotPose >::value();
  }
  static const char* value(const ::robot_planning::RobotPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_PLANNING_MESSAGE_ROBOTPOSE_H
