// Generated by gencpp from file robot_planning/RobotPoseResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_PLANNING_MESSAGE_ROBOTPOSERESPONSE_H
#define ROBOT_PLANNING_MESSAGE_ROBOTPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_planning
{
template <class ContainerAllocator>
struct RobotPoseResponse_
{
  typedef RobotPoseResponse_<ContainerAllocator> Type;

  RobotPoseResponse_()
    : transform()
    , success(false)
    , message()  {
    }
  RobotPoseResponse_(const ContainerAllocator& _alloc)
    : transform(_alloc)
    , success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _transform_type;
  _transform_type transform;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::robot_planning::RobotPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_planning::RobotPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotPoseResponse_

typedef ::robot_planning::RobotPoseResponse_<std::allocator<void> > RobotPoseResponse;

typedef boost::shared_ptr< ::robot_planning::RobotPoseResponse > RobotPoseResponsePtr;
typedef boost::shared_ptr< ::robot_planning::RobotPoseResponse const> RobotPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_planning::RobotPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_planning::RobotPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_planning::RobotPoseResponse_<ContainerAllocator1> & lhs, const ::robot_planning::RobotPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.transform == rhs.transform &&
    lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_planning::RobotPoseResponse_<ContainerAllocator1> & lhs, const ::robot_planning::RobotPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_planning::RobotPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_planning::RobotPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_planning::RobotPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_planning::RobotPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_planning::RobotPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_planning::RobotPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_planning::RobotPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56fdb6d4914112e35dd8259f93da86cf";
  }

  static const char* value(const ::robot_planning::RobotPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56fdb6d4914112e3ULL;
  static const uint64_t static_value2 = 0x5dd8259f93da86cfULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_planning::RobotPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_planning/RobotPoseResponse";
  }

  static const char* value(const ::robot_planning::RobotPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_planning::RobotPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] transform       # [x, y, z, qx, qy, qz, qw] 源坐标系到目标坐标系的变换\n"
"bool success\n"
"string message \n"
;
  }

  static const char* value(const ::robot_planning::RobotPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_planning::RobotPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.transform);
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_planning::RobotPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_planning::RobotPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "transform[]" << std::endl;
    for (size_t i = 0; i < v.transform.size(); ++i)
    {
      s << indent << "  transform[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.transform[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_PLANNING_MESSAGE_ROBOTPOSERESPONSE_H
