// Generated by gencpp from file robot_control/GetBaseLinkPoseResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_GETBASELINKPOSERESPONSE_H
#define ROBOT_CONTROL_MESSAGE_GETBASELINKPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace robot_control
{
template <class ContainerAllocator>
struct GetBaseLinkPoseResponse_
{
  typedef GetBaseLinkPoseResponse_<ContainerAllocator> Type;

  GetBaseLinkPoseResponse_()
    : base_link_pose()  {
    }
  GetBaseLinkPoseResponse_(const ContainerAllocator& _alloc)
    : base_link_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _base_link_pose_type;
  _base_link_pose_type base_link_pose;





  typedef boost::shared_ptr< ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetBaseLinkPoseResponse_

typedef ::robot_control::GetBaseLinkPoseResponse_<std::allocator<void> > GetBaseLinkPoseResponse;

typedef boost::shared_ptr< ::robot_control::GetBaseLinkPoseResponse > GetBaseLinkPoseResponsePtr;
typedef boost::shared_ptr< ::robot_control::GetBaseLinkPoseResponse const> GetBaseLinkPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator1> & lhs, const ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.base_link_pose == rhs.base_link_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator1> & lhs, const ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4dd5c128d0b36079967e1c67bbeccd38";
  }

  static const char* value(const ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4dd5c128d0b36079ULL;
  static const uint64_t static_value2 = 0x967e1c67bbeccd38ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control/GetBaseLinkPoseResponse";
  }

  static const char* value(const ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response: 位姿\n"
"geometry_msgs/Pose base_link_pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.base_link_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetBaseLinkPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control::GetBaseLinkPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "base_link_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.base_link_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_GETBASELINKPOSERESPONSE_H
