// Generated by gencpp from file robot_control/GetBaseLinkPoseRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_GETBASELINKPOSEREQUEST_H
#define ROBOT_CONTROL_MESSAGE_GETBASELINKPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_control
{
template <class ContainerAllocator>
struct GetBaseLinkPoseRequest_
{
  typedef GetBaseLinkPoseRequest_<ContainerAllocator> Type;

  GetBaseLinkPoseRequest_()
    : joint_angles_branch1()
    , joint_angles_branch4()  {
    }
  GetBaseLinkPoseRequest_(const ContainerAllocator& _alloc)
    : joint_angles_branch1(_alloc)
    , joint_angles_branch4(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_angles_branch1_type;
  _joint_angles_branch1_type joint_angles_branch1;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_angles_branch4_type;
  _joint_angles_branch4_type joint_angles_branch4;





  typedef boost::shared_ptr< ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetBaseLinkPoseRequest_

typedef ::robot_control::GetBaseLinkPoseRequest_<std::allocator<void> > GetBaseLinkPoseRequest;

typedef boost::shared_ptr< ::robot_control::GetBaseLinkPoseRequest > GetBaseLinkPoseRequestPtr;
typedef boost::shared_ptr< ::robot_control::GetBaseLinkPoseRequest const> GetBaseLinkPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator1> & lhs, const ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint_angles_branch1 == rhs.joint_angles_branch1 &&
    lhs.joint_angles_branch4 == rhs.joint_angles_branch4;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator1> & lhs, const ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d997c570f966380228b6d56ed45cae97";
  }

  static const char* value(const ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd997c570f9663802ULL;
  static const uint64_t static_value2 = 0x28b6d56ed45cae97ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control/GetBaseLinkPoseRequest";
  }

  static const char* value(const ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] joint_angles_branch1\n"
"float64[] joint_angles_branch4\n"
"\n"
;
  }

  static const char* value(const ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_angles_branch1);
      stream.next(m.joint_angles_branch4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetBaseLinkPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control::GetBaseLinkPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_angles_branch1[]" << std::endl;
    for (size_t i = 0; i < v.joint_angles_branch1.size(); ++i)
    {
      s << indent << "  joint_angles_branch1[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_angles_branch1[i]);
    }
    s << indent << "joint_angles_branch4[]" << std::endl;
    for (size_t i = 0; i < v.joint_angles_branch4.size(); ++i)
    {
      s << indent << "  joint_angles_branch4[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_angles_branch4[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_GETBASELINKPOSEREQUEST_H
