// Generated by gencpp from file robot_control/GetBaseLinkPose.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_GETBASELINKPOSE_H
#define ROBOT_CONTROL_MESSAGE_GETBASELINKPOSE_H

#include <ros/service_traits.h>


#include <robot_control/GetBaseLinkPoseRequest.h>
#include <robot_control/GetBaseLinkPoseResponse.h>


namespace robot_control
{

struct GetBaseLinkPose
{

typedef GetBaseLinkPoseRequest Request;
typedef GetBaseLinkPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBaseLinkPose
} // namespace robot_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_control::GetBaseLinkPose > {
  static const char* value()
  {
    return "124f2f1fb4bf270787e14bd14a8d0a4b";
  }

  static const char* value(const ::robot_control::GetBaseLinkPose&) { return value(); }
};

template<>
struct DataType< ::robot_control::GetBaseLinkPose > {
  static const char* value()
  {
    return "robot_control/GetBaseLinkPose";
  }

  static const char* value(const ::robot_control::GetBaseLinkPose&) { return value(); }
};


// service_traits::MD5Sum< ::robot_control::GetBaseLinkPoseRequest> should match
// service_traits::MD5Sum< ::robot_control::GetBaseLinkPose >
template<>
struct MD5Sum< ::robot_control::GetBaseLinkPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_control::GetBaseLinkPose >::value();
  }
  static const char* value(const ::robot_control::GetBaseLinkPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_control::GetBaseLinkPoseRequest> should match
// service_traits::DataType< ::robot_control::GetBaseLinkPose >
template<>
struct DataType< ::robot_control::GetBaseLinkPoseRequest>
{
  static const char* value()
  {
    return DataType< ::robot_control::GetBaseLinkPose >::value();
  }
  static const char* value(const ::robot_control::GetBaseLinkPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_control::GetBaseLinkPoseResponse> should match
// service_traits::MD5Sum< ::robot_control::GetBaseLinkPose >
template<>
struct MD5Sum< ::robot_control::GetBaseLinkPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_control::GetBaseLinkPose >::value();
  }
  static const char* value(const ::robot_control::GetBaseLinkPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_control::GetBaseLinkPoseResponse> should match
// service_traits::DataType< ::robot_control::GetBaseLinkPose >
template<>
struct DataType< ::robot_control::GetBaseLinkPoseResponse>
{
  static const char* value()
  {
    return DataType< ::robot_control::GetBaseLinkPose >::value();
  }
  static const char* value(const ::robot_control::GetBaseLinkPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_GETBASELINKPOSE_H
